// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Witcher3IngredientsMVC.Data;

#nullable disable

namespace Witcher3IngredientsMVC.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251110132258_meong")]
    partial class meong
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.21");

            modelBuilder.Entity("Witcher3IngredientsMVC.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Witcher3IngredientsMVC.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("Witcher3IngredientsMVC.Models.ItemLink", b =>
                {
                    b.Property<int>("SourceItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ResultItemId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SourceItemId", "ResultItemId");

                    b.HasIndex("ResultItemId");

                    b.ToTable("ItemLinks");
                });

            modelBuilder.Entity("Witcher3IngredientsMVC.Models.Item", b =>
                {
                    b.HasOne("Witcher3IngredientsMVC.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Witcher3IngredientsMVC.Models.ItemLink", b =>
                {
                    b.HasOne("Witcher3IngredientsMVC.Models.Item", "ResultItem")
                        .WithMany("DismantleFromLinks")
                        .HasForeignKey("ResultItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Witcher3IngredientsMVC.Models.Item", "SourceItem")
                        .WithMany("DismantleIntoLinks")
                        .HasForeignKey("SourceItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ResultItem");

                    b.Navigation("SourceItem");
                });

            modelBuilder.Entity("Witcher3IngredientsMVC.Models.Item", b =>
                {
                    b.Navigation("DismantleFromLinks");

                    b.Navigation("DismantleIntoLinks");
                });
#pragma warning restore 612, 618
        }
    }
}
