// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Witcher3IngredientsMVC.Data;

#nullable disable

namespace Witcher3IngredientsMVC.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251111141619_mgktr")]
    partial class mgktr
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.21");

            modelBuilder.Entity("Witcher3IngredientsMVC.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Witcher3IngredientsMVC.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("Witcher3IngredientsMVC.Models.ItemLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ResultItemId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("ResultItemId");

                    b.ToTable("ItemLinks");
                });

            modelBuilder.Entity("Witcher3IngredientsMVC.Models.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("Witcher3IngredientsMVC.Models.RecipeRequirement", b =>
                {
                    b.Property<int>("RecipeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("RecipeId", "ItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("RecipeRequirements");
                });

            modelBuilder.Entity("Witcher3IngredientsMVC.Models.Item", b =>
                {
                    b.HasOne("Witcher3IngredientsMVC.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Witcher3IngredientsMVC.Models.ItemLink", b =>
                {
                    b.HasOne("Witcher3IngredientsMVC.Models.Item", null)
                        .WithMany("DismantleIntoLinks")
                        .HasForeignKey("ItemId");

                    b.HasOne("Witcher3IngredientsMVC.Models.Item", "ResultItem")
                        .WithMany()
                        .HasForeignKey("ResultItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ResultItem");
                });

            modelBuilder.Entity("Witcher3IngredientsMVC.Models.RecipeRequirement", b =>
                {
                    b.HasOne("Witcher3IngredientsMVC.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Witcher3IngredientsMVC.Models.Recipe", "Recipe")
                        .WithMany("Requirements")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Witcher3IngredientsMVC.Models.Item", b =>
                {
                    b.Navigation("DismantleIntoLinks");
                });

            modelBuilder.Entity("Witcher3IngredientsMVC.Models.Recipe", b =>
                {
                    b.Navigation("Requirements");
                });
#pragma warning restore 612, 618
        }
    }
}
